version: '2'
services: 
  RabbitMQ:
    image: rabbitmq:3-management
    ports:
      - 5672:7672
      - 15672:15672
  
  ImageDB:
    image: fpommerening/devopenspace2016:picflow-database
    ports:
      - 5432:5432
  
  DocumentDB:
    image: mongo:3.2
    ports:
      - 27017:27017
    
  ExternalDB:
    image: mongo:3.2

  WebApp:
    image: fpommerening/devopenspace2016:picflow-webapp
    depends_on:
      - RabbitMQ
      - ImageDB
      - DocumentDB
    hostname: webapp
    ports:
      - 8000:8000
    environment:
      - ConnectionStringRabbitMQ=host=RabbitMQ
      - ConnectionStringImageDB=host=ImageDB;database=devspace;password=leipzig;username=devspace
      - ConnectionStringDocumentDB=mongodb://DocumentDB
    
  ExtApp:
    image: fpommerening/devopenspace2016:picflow-extapp
    depends_on:
      - RabbitMQ
      - ImageDB
      - DocumentDB
    hostname: extapp
    ports:
      - 5000:5000
    environment:
      - ConnectionStringEntryDB=mongodb://ExternalDB
    
  Uploader:
    image: fpommerening/devopenspace2016:picflow-uploader
    depends_on:
      - RabbitMQ
      - DocumentDB
      - ExtApp
    hostname: uploader
    environment:
      - ConnectionStringRabbitMQ=host=RabbitMQ
      - ConnectionStringImageDB=host=ImageDB;database=devspace;password=leipzig;username=devspace
      - ExternalAppUrl=http://extapp:8000/api/postimage
    
  Processor:
    image: fpommerening/devopenspace2016:picflow-processor
    depends_on:
      - RabbitMQ
      - DocumentDB
    hostname: processor
    environment:
      - ConnectionStringRabbitMQ=host=RabbitMQ
      - ConnectionStringDocumentDB=mongodb://DocumentDB
    
  Authorization:
    image: fpommerening/devopenspace2016:picflow-authorization
    depends_on:
      - RabbitMQ
      - DocumentDB
    hostname: authorization
    environment:
      - ConnectionStringRabbitMQ=host=RabbitMQ
      - ConnectionStringImageDB=host=ImageDB;database=devspace;password=leipzig;username=devspace
    
  Persistor:
    image: fpommerening/devopenspace2016:picflow-persistor
    depends_on:
      - RabbitMQ
      - ImageDB
      - DocumentDB
    hostname: persistor
    environment:
      - ConnectionStringRabbitMQ=host=RabbitMQ
      - ConnectionStringImageDB=host=ImageDB;database=devspace;password=leipzig;username=devspace
      - ConnectionStringDocumentDB=mongodb://DocumentDB

