version: '2'
services: 
  rabbitmq:
    image: rabbitmq:3-management

  mongo:
    image: mongo:3.2

  compose:
    image: dduportal/docker-compose
    
  weblogger:
    image: fpommerening/devopenspace2016:logging-web
    
  loadbalancer:
    image: fpommerening/devopenspace2016:logging-loadbalancer
    
  console:
    image: fpommerening/devopenspace2016:logging-console
    
  caller:
    image: fpommerening/devopenspace2016:logging-caller

  web:
    depends_on:
      - rabbitmq
      - mongo
    image: fpommerening/devopenspace2016:StartUpApp
    ports:
      - 15106:15106